src/Wrappers/MollieApiWrapper.php

https://www.mollie.com/nl/docs/reference/refunds/list-all

Add refunds method

---

README.md

I've added a basic example for recurring payments to the README. Since it's a fairly new product of Mollie it might come in useful for people trying to figure this out. I know it's in the documentations aswel, but perhaps this is also a good place to have an example ready to use.
Easy to find example to recurring payments, I had to find the info from a few spots before getting there. This is a ready to go example.
-
-
Readme change

Recurring example in README

---

config/mollie.php

Add note that mollie only needs to be added to services.php for Mollie Connect.

Add note that mollie only needs to be added to services.php for Connect

---

README.md

Fix casing in example code.
Extending on #32

Fix casing

---

CHANGELOG.md
README.md
docs/recurring_and_direct_charge.md
docs/webhook.md

V2 stable release. Includes documentation updates for #52 (named webhook route examples).
[Travis](https://travis-ci.org/sandervanhooft/laravel-mollie/builds/401706458)

V2 stable release

---

README.md
docs/recurring_and_direct_charge.md
docs/roadmap.md

Laravel Spark support will be researched when/if Cashier-Mollie is finished. This is added to the roadmap.
Additionally, redirect examples have been added to the normal payment and mandate payment examples.
Good docs = happy users.
No tests required, only updated the docs.

Docs: Roadmap includes Laravel Spark, payments include redirect examples.

---

composer.json
src/helpers.php
tests/HelpersTest.php

To cleanup the facade/method `\Mollie::api()` to just only a (helper)-function `mollie()`
See above
tests/HelpersTest.php

Added helper file/function for mollie() to \Mollie::api()

---

README.md

Added `mollie()` helper method instructions.
Accompanies the introduction of the `mollie()` helper in v2.1.0.
Documentation only.

Updated readme for v2.1.0 release

---

docs/roadmap.md

Added Laravel Nova plugin and more details on the webhook implementation to the roadmap. Plus some minor text edits for readability.

Added Laravel Nova plugin to roadmap

---

CHANGELOG.md
composer.json
src/Wrappers/MollieApiWrapper.php
tests/Wrappers/MollieApiWrapperTest.php

Support for Orders, Shipments and Captures API.

---

CHANGELOG.md

Preparing v2.3.1 release

---

src/MollieConnectProvider.php
src/Wrappers/MollieApiWrapper.php

Fixes documentation blocks so that IDE's follow proper auto completion.
Auto completion was not proper in IDE's like PhpStorm.
phpunit with on ubuntu with xdebug.

Fix DocBlocks

---

.travis.yml

Completely reworked Travis file, allowing for legacy testing. Also permits `nightly` build to fail.

Travis: Laravel legacy testing

---

README.md

Laravel-mollie doesn't work with a fresh Lumen installation.
n/a
n/a
n/a

Fix documentation for Laravel Lumen

---

.gitignore
.travis.yml
composer.json
src/MollieConnectProvider.php
tests/MollieConnectProviderTest.php

Drop support for Laravel versions prior to 5.8.
Fix #110

Purge old laravels, fix #110

---

.travis.yml
composer.json

Laravel 7.x

---

README.md

#70 did you mean it like this? @sandervanhooft 
I just changed every `Mollie::api()->payments()` to `Mollie::api()->payments`.
I also added the metadata from the [docs](https://docs.mollie.com/reference/v2/payments-api/create-payment#example).
I could also make a new header image but I can't upload it to [https://info.mollie.com/hubfs/github/laravel/editor.png](https://info.mollie.com/hubfs/github/laravel/editor.png)
where the current header image is.

Update docs with properties

---

README.md

Update create-payment example

---

src/Wrappers/MollieApiWrapper.php
tests/Wrappers/MollieApiWrapperTest.php

Add profileMethods method to MollieApiWrapper

---

.github/workflows/tests.yml

Update tests.yml - PHP 8.1 

---

src/MollieLaravelHttpClientAdapter.php
tests/Wrappers/MollieApiLaravelClientTest.php

fix issue with double headers

---

README.md

Version removed, so that the current package version is always taken
composer.json package version updated
This makes installation easier, as the command or snippet can simply be copied and the latest version is used
No tests necessary

Update readme for easier copy of code snippets

---

.github/workflows/tests.yml

Add testing on PHP 8.2 to GitHub workflow.
PHP 8.2 has been released recently (see also https://www.php.net/releases/8.2/en.php).
This ensures tests for this package are run on this PHP version.

Add testing on PHP 8.2 to GitHub workflow

---

composer.json
src/Wrappers/MollieApiWrapper.php
tests/Wrappers/MollieApiWrapperTest.php

adds client link endpoint from mollie-api-php SDK

add client link endpoint

---

.github/workflows/tests.yml

Add PHP 8.3 to CI test runs.
With a few RC's released and the final release coming up in november, it might be a good thing to start running tests on the new PHP.
See also https://github.com/mollie/mollie-api-php/pull/697.
n/a

Run CI tests on PHP 8.3

---

README.md

Update signup url (original gives 404)
