README.md

You should use the `provider` option to limit the publishing of assets to your own package. More info: https://murze.be/2016/04/publishing-package-assets-right-way/

Avoid publishing assets of other packages

---

.gitattributes
.gitignore
.travis.yml
composer.json
config/mollie.php
phpunit.xml.dist
src/MollieServiceProvider.php
tests/Facades/MollieTest.php
tests/MollieManagerTest.php
tests/MollieServiceProviderTest.php
tests/TestCase.php

I've provided basic tests cases for laravel's service provider and support for integration in [Travis CI](https://travis-ci.org/).
You should also use [StyleCI](https://styleci.io/) for linearise editing style between contributors.
Tests are OK without Socialite but fail with it...
Deep tests for socialite driver are left to do.

Add basic tests + Travis CI integration

---

phpunit.xml.dist

This a temporary fix in order to get back tests to green

Temporary disable processing uncovered files

---

.gitignore
composer.json
phpunit.xml.dist
src/MollieServiceProvider.php
src/Wrappers/MollieApiWrapper.php
tests/MollieConnectProviderTest.php
tests/MollieServiceProviderTest.php
tests/TestCase.php
tests/Wrappers/MollieApiWrapperTest.php

I've writted tests for Socialite plugins.
I decided to put the root class of your API in the container because of testability.
After some research, I think you should extract your provider for Socialite in another repository such as [this](https://github.com/SocialiteProviders/Twitch) by using [SocialiteProvider](https://github.com/SocialiteProviders) and [reference it.](https://socialiteproviders.github.io/#contribute)
I can develop the repository if you want.
For now, if Socialite is not loaded, tests are marked as skipped.
I've also writed some tests for the API Wrapper, but more tests are useless because in the end it's just a wrapper and tests are in the root mollie-api-php repository.

Add tests for Socialite

---

src/MollieConnectProvider.php

A method which let a user obtain an access token with a valid Refresh token 
This fixes issue https://github.com/mollie/laravel-mollie/issues/22, all credits go to @gtapps

Add method to get an access token with a refresh token

---

.gitignore
.travis.yml
README.md
docs/mollie_connect.md
docs/recurring_and_direct_charge.md
docs/roadmap.md
docs/webhook.md

#51: Build against php nightly. Dropped `hhvm` support and `--prefer-lowest`.
#49: Restructured readme / docs. Dropped obsolete Mollie Connect setup snippet from docs.
Travis: https://travis-ci.org/sandervanhooft/laravel-mollie/builds/399950790

Fix issues #51 and #49

---

.github/PULL_REQUEST_TEMPLATE.md

The github PR template does not offer a "documentation only" option. While documenting the past few PRs, I had to include it manually. (In this PR as well)

Added documentation-only option to PR template

---

src/Wrappers/MollieApiWrapper.php
tests/Wrappers/MollieApiWrapperTest.php

Added wrapper methods for `organizations()` and `permissions()`.
Organization and Permission endpoints were introduced in the core Mollie php client. These wrapper methods allow you to use these endpoints with Laravel Mollie.
PHPunit, Travis.

Added support for organizations and permissions

---

README.md

For most payment types the `redirectUrl` field is required

add redirectUrl to example payment

---

src/MollieServiceProvider.php

`MollieConnectProvider` was not loaded from the `MollieServiceProvider`, because the latter was configured to load in a `deferred` way. Therefore (the condition check wether to load) the `MollieConnectProvider` was never fired.
For now, I'm disabling `deferred` loading.
Another (perhaps cleaner) solution would be to provide a separate `MollieConnectServiceProvider` for conditionally loading the `MollieConnectProvider`. This would enable the `MollieServiceProvider` and the `MollieConnectServiceProvider` to be both loaded with `deferred` enabled. As this may cause a BC, its' interesting to look at for a later major release.
Fixes #73.
Phpunit and manually (see issue #73).

Disabled deferred loading to fix Socialite issue (#73).

---

composer.json
src/Wrappers/MollieApiWrapper.php
tests/Wrappers/MollieApiWrapperTest.php

Added the root chargeback endpoint to the mollie client wrapper. The chargeback endpoint was added to the mollie core client v2.1.6, so that dependency version also is bumped in composer.

Support for (root) chargebacks endpoint

---

.travis.yml
composer.json
tests/MollieConnectProviderTest.php
tests/Wrappers/MollieApiWrapperTest.php

Adds support for Laravel 6.*
Additionally, rewrote some tests to let it work nicely with latest version of PHPUnit.

Add support for Laravel 6.*

---

README.md
src/Wrappers/MollieApiWrapper.php
tests/Wrappers/MollieApiWrapperTest.php

The API Wrapper wrapped the properties in methods i.e. `mollie()->payments()`.
Now it is also accessible via magic getter i.e. `mollie()->payments`.
Implements #70 
Added a test to `Mollie\Laravel\Tests\Wrappers\MollieApiWrapperTest` where all endpoints are tested with properties.
It was also tested in a fresh laravel 7.x application

Add dynamic calls via property

---

tests/TestCase.php

The signature of the `TestCase::getServiceProviderClass` method was updated in Graham Campbell's test suite. This change reflects that, allowing the GitHub action tests to run again.

getServiceProviderClass update

---

src/Wrappers/MollieApiWrapper.php
tests/Wrappers/MollieApiWrapperTest.php

Added 2 new methods `enableDebugging()` and `disableDebugging()` to `MollieApiWrapper` which were introduced in Mollie API PHP client [v2.40.0](https://github.com/mollie/mollie-api-php/releases/tag/v2.40.0).
Make it possible to use these new methods in this package.
I have some troubles with 401 errors on the profiles endpoint with my project, and I need to see the request details.
See tests.

Added enable- and disable debugging mode API client

---

README.md

This makes it easier to copy & paste the commands directly in the terminal (instead of manually removing the `$` at the front).

Update readme for easier copy of code snippets

---

src/helpers.php

Add a return property to the `mollie()` helper for IDE autocompletion.
It simply adds a return-statement in the docblock.
As a lazy programmer myself I don't like looking up every function when using the function helper.
Add the docblock to the function and see the magic your editor does :)

Add docblock to mollie() helper method

---

src/Wrappers/MollieApiWrapper.php
tests/Wrappers/MollieApiWrapperTest.php

When installing this package it will throw an exception if the `MOLLIE_KEY` is not yet set in `.env`. This halts booting the whole sequence of Laravel service providers. This PR fixes that.

Allow empty mollie key

---

src/MollieLaravelHttpClientAdapter.php
src/MollieServiceProvider.php

Http client adapter

---

phpunit.xml.dist

Auto-migrates PHPUnit configuration to match latest configuration scheme.
When running `vendor/bin/phpunit` with the current configuration, the package suggests to (automatically) migrate the configuration to the latest schema. This PR applies the auto-migration and slightly reworks the formatting in this file.

Auto-migrate PHPunit configuration

---

.github/workflows/tests.yml

Use latest `actions/checkout` version in tests workflow.
The current tests workflow uses `actions/checkout@v2`, which triggers a deprecation warning. This PR updates the version to remove the warnings.

Use actions/checkout@v3 in tests workflow

---

docs/mollie_connect.md

As of v3 of the package it should be 
`Mollie::api()->profiles->page()` instead of `->profiles()`
Better documentation for newcomers
Documentation only (no code changes)

Update mollie_connect documentation to reflect v3 change
